---
    linters:
      yamllint:
        config: ./yamllint.conf

    review:
      # Don't use 'failure' build status when a pull request
      # contains style errors.
      fail_on_comments: false
